### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Leilei-Huang-work** [kyegomez/VisionMamba#12]
![image](https://github.com/kyegomez/VisionMamba/assets/57476896/fb18d727-583c-4ae3-8719-5c8b203d8824)

**Comment by kyegomez** [comment]
@Leilei-Huang-work Update your zetascale

`pip3 install -U zetascale`

**Comment by Leilei-Huang-work** [comment]
Thank you for answering my question. But now I have another bug，Please help me out, thank you。
![image](https://github.com/kyegomez/VisionMamba/assets/57476896/54fc0b33-b6af-433a-ba23-0d78d1d351bb)

**Comment by kyegomez** [comment]
@Leilei-Huang-work fixed
