### ISSUE TITLE
[BUG] RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 256] but got: [1, 196].

### ISSUE THREAD

**Issue by MIOS9** [kyegomez/VisionMamba#15]
**Describe the bug**
just run example.py and you can see the error.

**To Reproduce**
1. `cd VisionMamba`
2. `python example.py`
3. See error

**Expected behavior**
I've done nothing , just run the code which given by the author.

**Screenshots**

![2024-04-03 21-49-47屏幕截图](https://github.com/kyegomez/VisionMamba/assets/146852649/1d619c70-07f0-4526-adee-5ee3fcedff66)

**Comment by Programmergg** [comment]
<img width="911" alt="test" src="https://github.com/kyegomez/VisionMamba/assets/32862873/7f2b95d6-fa5a-4bbe-a665-c76f8fd525fb">
I also encountered this error. Upon investigation, the issue arises at this step where matrix multiplication of two tensors of size torch.Size([1, 197, 256]) is not valid. Should we instead use element-wise multiplication using '*' (with which the code runs correctly)? Additionally, I have a question regarding the authors' statement in the paper about using cls_token, which appears to be commented out in their open-source code. Could this be an oversight?

**Comment by AirPlanBird** [comment]
Hey,bro, I have the same question as you, not only (RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 256] but got: [1, 196]), I also think there should be a problem with the tensor splicing part being commented out!
![屏幕截图 2024-04-14 182548](https://github.com/kyegomez/VisionMamba/assets/166970222/af2666ca-8be7-4155-b6ba-a95b0ef128f5)
![屏幕截图 2024-04-14 182629](https://github.com/kyegomez/VisionMamba/assets/166970222/fde3f870-0295-47ae-b511-2e5c01105cc5)
But after changing the image size to 256*256, it can be run successfully, I think the most important question is where cls_token is commented out, I don't understand, I use it for training results acc is very poor.

**Comment by Programmergg** [comment]
As previously stated, by altering the image size to 256 and considering a patch size of 16, the initial torch dimensions of `torch.Size([1, 196, 256])` corresponding to an image size of 224 are transformed to `torch.Size([1, 256, 256])`. Although matrix multiplication between two `torch.Size([1, 256, 256])` matrices is technically feasible, this procedure appears illogical; therefore, employing element-wise multiplication (Hadamard product) might be a more rational approach. Additionally, the authors assert in the paper that positioning the `cls_token` centrally within the patch dimension can yield superior results, an aspect that could be crucial.

**Comment by AirPlanBird** [comment]
It's true that I didn't think carefully about the problem of tensor mismatch, mainly because the training effect I used for image classification was a bit poor, and I thought it might be a problem with cls_token being annotated

**Comment by kyegomez** [comment]
@Programmergg @AirPlanBird it's fixed, I wasn't finished with the forward and backward implementations
