### ISSUE TITLE
[BUG] Swarms is required to install but not used

### ISSUE THREAD

**Issue by MelihDarcanxyz** [kyegomez/VisionMamba#18]
**Describe the bug**
Another package that isn't used in this package is in [requirements](https://github.com/kyegomez/VisionMamba/blob/31076700f403346658ff567fa249379ce87b8f6a/requirements.txt#L3C1-L3C7).

**To Reproduce**
Install the package from pip

**Expected behavior**
Install necessary packages

**Additional context**
I see the author is the author of `swarms` package too. So if possible, can you clarify why such requirement is needed. I've checked that package too, but it's unrelated.

**Comment by kyegomez** [comment]
@MelihDarcanxyz fixed, deleted it!
