### ISSUE TITLE
[BUG] Inconsistent Tensor Dimensions

### ISSUE THREAD

**Issue by MelihDarcanxyz** [kyegomez/VisionMamba#20]
**Describe the bug**
Saw this from the discord, and am able to reproduce exactly. Copying the message:

I'm getting inconsistent tensor output shapes. Does anyone know anything about this? I'll provide some examples:

1. `Input tensor shape: torch.Size([1, 3, 224, 224])`
`Output tensor shape: torch.Size([1, 196, 10])`

224 -> 196

2. `Input tensor shape: torch.Size([1, 3, 16, 16])`
`Output tensor shape: torch.Size([1, 1, 10])`

16 -> 1

3. `Input tensor shape: torch.Size([1, 3, 256, 256])`
`Output tensor shape: torch.Size([1, 256, 10])`

256 -> 256

The model used is:

```python
model = Vim(
    dim=256,
    heads=8,
    dt_rank=32,
    dim_inner=256,
    d_state=256,
    num_classes=10,
    image_size=IMAGE_SIZE,
    patch_size=16,
    channels=IMAGE_CHANNELS,
    dropout=0.1,
    depth=12,
)
```

If it's consistent, what's the math behind this? Or is this a BUG?

**Comment by kyegomez** [comment]
@MelihDarcanxyz look at the num classes, the last dimension is the number of classes. This isn't random output. Read the code

**Comment by MelihDarcanxyz** [comment]
> @MelihDarcanxyz look at the num classes, the last dimension is the number of classes. This isn't random output. Read the code

Yeah I did. The number of classes is constant in every example (10), yet the relation changes between input and output tensor. Please read the issue again.

**Comment by kyegomez** [comment]
@MelihDarcanxyz its fixed now!
