### ISSUE TITLE
[BUG] `heads` parameter is defined but not used in `VisionEncoderMambaBlock`

### ISSUE THREAD

**Issue by MelihDarcanxyz** [kyegomez/VisionMamba#21]
`heads` parameter is defined but not used in `VisionEncoderMambaBlock`.

This line uses it to initialize  `VisionEncoderMambaBlock`:
https://github.com/kyegomez/VisionMamba/blob/68e6447d9e3a7e7bb369c227d667bbb88275ce2e/vision_mamba/model.py#L235

But it has no use in `VisionEncoderMambaBlock` as can be seen from here:

https://github.com/kyegomez/VisionMamba/blob/68e6447d9e3a7e7bb369c227d667bbb88275ce2e/vision_mamba/model.py#L32C1-L135C17

**Comment by kyegomez** [comment]
@MelihDarcanxyz just fixed
