### ISSUE TITLE
forward-backward ssm

### ISSUE THREAD

**Issue by swarajnanda2021** [kyegomez/VisionMamba#3]
It appears, per algorithm 1 of the vision mamba paper, the state-space model runs bi-directionally along the sequence. But in this implementation I see that both forward and backward convolutions are standard 1D convolutions, rather than going backward and forward in space. Can you explain your rationale behind this?

Because otherwise, there seems to be no difference between the backward and forward operations, which would otherwise be providing the mamba block a bi-directional way of applying the state-space selection operation.

**Comment by kyegomez** [comment]
@swarajnanda2021 yes I did this for now until I can understand what forward and backward into space means

**Comment by swarajnanda2021** [comment]
Thanks for the fast response. Per the stencil operation used by most practitioners, it seems to me this is just a forward and backward for-looping in the scan process. Concur?

**Comment by thucz** [comment]
So the forward and backward SSM have no difference in fact?

**Comment by PunkGibsonLZ-debug** [comment]
> So the forward and backward SSM have no difference in fact?

From my understanding, there's no structural difference between them — the only distinction lies in the direction of the input sequence: the backward SSM receives the reversed version of the sequence.
